### ISSUE TITLE
Xp issue

### ISSUE THREAD

**Issue by SxRHunter** [Artillex-Studios/AxGraves#3] opened 2023-12-01 08:06 UTC
Something wrong with the xp, i got more xp then i had before death, had about 29 levels died, and now got 52.

**Comment by BenceX100** [comment] 2023-12-02 10:20
It is probably caused by some plugin or maybe keepinventory, can you show your plugin list?

**Comment by SxRHunter** [comment] 2023-12-02 21:13
Sorry for the late reply.
Weirdly the glitch only happens to me, the other players don't have any issue.
Plugins:
AxGraves, FastChunkPregenerator, SkinsRestorer, spark and Unstriplog.
Datapacks:
Armored elytra, Double shulker shells {Both are by vanillatweaks} and pk waystones.
No keep inventory enabled.
Server is purpur 1.20.2.

**Comment by BenceX100** [comment] 2023-12-23 15:21
Fixed in https://github.com/Artillex-Studios/AxGraves/releases/tag/1.4.1 thanks for reporting!

**Closed by BenceX100** 2023-12-23 15:21 UTC
